
#公共配置和表名当前配置文件
#thymeleaf模板、当前配置活跃文件
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro

#
#   mail:
#     host: 
#     username: 
#     password: 
# #    port: 
#     protocol: 
#     test-connection: true
#     default-encoding: utf-8
#   boot:
#     admin:
#       notify:
#         mail:
#           from: 


#数据持久层
mybatis:
  type-aliases-package: com.master.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png
